import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { Panel, SectionLabel } from '../components/UIBits';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { toast } from 'sonner';
import { Download, Printer, FileText } from 'lucide-react';

const TYPES = [
  { id: 'daily-safety', label: 'Daily Safety Report' },
  { id: 'environmental', label: 'Environmental Report' },
  { id: 'compliance', label: 'Compliance Report' },
  { id: 'incident', label: 'Incident Report' },
  { id: 'monthly', label: 'Monthly Mine Safety Report' },
];

const line = (label, value) => `${label.padEnd(28, ' ')}${value}\n`;

export default function Reports() {
  const { kpi, risk, sensors, alerts, incidents, complianceScore, complianceCategories, activeMine, mines, user } = useApp();
  const [type, setType] = useState('daily-safety');
  const [zoneFilter, setZoneFilter] = useState('all');
  const [from, setFrom] = useState(new Date(Date.now() - 86400e3).toISOString().slice(0, 10));
  const [to, setTo] = useState(new Date().toISOString().slice(0, 10));
  const [preview, setPreview] = useState(null);

  const buildReport = () => {
    const mineName = mines.find((m) => m.id === activeMine)?.name || activeMine;
    const t = TYPES.find((x) => x.id === type)?.label;
    let body = '';
    body += '============================================================\n';
    body += ' MineGuard AI — ' + t.toUpperCase() + '\n';
    body += '============================================================\n\n';
    body += line('Mine', mineName);
    body += line('Report Type', t);
    body += line('Zone Filter', zoneFilter);
    body += line('Date Range', `${from} → ${to}`);
    body += line('Generated', new Date().toLocaleString());
    body += line('Generated By', `${user?.name} (${user?.role})`);
    body += '\n--- KPI SNAPSHOT ---\n';
    body += line('Overall Safety', `${kpi.overallSafety}%`);
    body += line('Compliance Score', `${kpi.complianceScore}%`);
    body += line('Active Alerts', kpi.activeAlertCount);
    body += line('Critical Incidents', kpi.criticalIncidents);
    body += line('Workers Present', kpi.workersPresent);
    body += line('Connected Sensors', `${kpi.connectedSensors.active}/${kpi.connectedSensors.total}`);
    body += '\n--- AI RISK ENGINE ---\n';
    body += line('Risk Score', risk.score);
    body += line('Risk Category', risk.category);
    body += line('Recommendation', risk.recommendation);
    body += 'Contributing Factors:\n';
    if (risk.factors.length === 0) body += '  - None. System nominal.\n';
    risk.factors.forEach((f) => { body += `  - ${f.label} (+${f.weight})\n`; });
    body += '\n--- SENSOR SUMMARY ---\n';
    sensors.forEach((s) => { body += line(`${s.id} ${s.label}`, `${s.value.toFixed(2)} ${s.unit}  [warn ${s.warn} / crit ${s.crit}]`); });
    body += '\n--- COMPLIANCE ---\n';
    body += line('Overall Compliance', `${complianceScore}%`);
    complianceCategories.forEach((c) => { body += line(`  ${c.label}`, `${c.score}%  (${c.passed} passed / ${c.failed} failed / ${c.pending} pending)`); });
    body += '\n--- ALERTS (recent) ---\n';
    alerts.slice(0, 10).forEach((a) => { body += `${new Date(a.ts).toLocaleString()}  [${a.severity.toUpperCase()}] ${a.id}  ${a.description}\n`; });
    if (alerts.length === 0) body += '  (none)\n';
    body += '\n--- INCIDENTS ---\n';
    incidents.slice(0, 10).forEach((i) => { body += `${i.id}  [${i.severity}]  ${i.category} @ ${i.zone}  — ${i.status}\n`; });
    if (incidents.length === 0) body += '  (none)\n';
    body += '\n============================================================\n';
    body += ' Demo report. Real-world deployment requires certified sensors,\n';
    body += ' validated AI models, regulatory approval and safety procedures.\n';
    body += '============================================================\n';
    return body;
  };

  const generate = () => {
    const body = buildReport();
    setPreview(body);
    toast.success('Report generated', { description: TYPES.find((x) => x.id === type)?.label });
  };

  const download = () => {
    if (!preview) return;
    const blob = new Blob([preview], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mineguard-${type}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  const printReport = () => {
    if (!preview) return;
    const w = window.open('', '_blank');
    w.document.write(`<pre style="font-family: 'JetBrains Mono', monospace; padding: 24px; white-space: pre-wrap;">${preview.replace(/</g, '&lt;')}</pre>`);
    w.document.title = 'MineGuard Report';
    w.print();
  };

  return (
    <div className="space-y-5" data-testid="reports-page">
      <div>
        <SectionLabel>Reports</SectionLabel>
        <h1 className="font-heading font-bold text-3xl mt-1">Automated Compliance & Safety Reports</h1>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Panel className="p-5 lg:col-span-1">
          <SectionLabel>Configure Report</SectionLabel>
          <div className="mt-3 space-y-3">
            <div>
              <Label className="text-xs uppercase tracking-widest text-zinc-500">Report Type</Label>
              <div className="mt-2 flex flex-wrap gap-1">
                {TYPES.map((t) => (
                  <button key={t.id} onClick={() => setType(t.id)} className={`text-xs px-2.5 py-1.5 rounded-sm border ${type === t.id ? 'bg-white/10 border-white/25' : 'border-white/10 hover:border-white/20'}`} data-testid={`rt-${t.id}`}>{t.label}</button>
                ))}
              </div>
            </div>
            <div>
              <Label className="text-xs uppercase tracking-widest text-zinc-500">From</Label>
              <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="mt-1 bg-[#0F1116] border-white/10 rounded-sm" data-testid="report-from" />
            </div>
            <div>
              <Label className="text-xs uppercase tracking-widest text-zinc-500">To</Label>
              <Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1 bg-[#0F1116] border-white/10 rounded-sm" data-testid="report-to" />
            </div>
            <div>
              <Label className="text-xs uppercase tracking-widest text-zinc-500">Zone</Label>
              <Input value={zoneFilter} onChange={(e) => setZoneFilter(e.target.value)} placeholder="all" className="mt-1 bg-[#0F1116] border-white/10 rounded-sm" data-testid="report-zone" />
            </div>
            <div className="flex gap-2 pt-1">
              <Button className="rounded-sm bg-blue-600 hover:bg-blue-700 gap-2 flex-1" onClick={generate} data-testid="btn-generate-report"><FileText size={14} /> Generate</Button>
              <Button className="rounded-sm bg-emerald-600 hover:bg-emerald-700 gap-2" onClick={download} disabled={!preview} data-testid="btn-download-report"><Download size={14} /> Download</Button>
              <Button variant="ghost" className="rounded-sm hover:bg-white/10 gap-2" onClick={printReport} disabled={!preview} data-testid="btn-print-report"><Printer size={14} /> Print</Button>
            </div>
          </div>
        </Panel>

        <Panel className="p-5 lg:col-span-2">
          <SectionLabel>Preview</SectionLabel>
          <div className="mt-3 border border-white/10 rounded-sm bg-[#0B0D11] p-4 max-h-[560px] overflow-auto">
            {preview ? (
              <pre className="text-[11px] leading-relaxed font-mono-data text-zinc-300 whitespace-pre-wrap" data-testid="report-preview">{preview}</pre>
            ) : (
              <div className="text-sm text-zinc-500 text-center py-10">Configure and click <span className="text-white font-medium">Generate</span> to preview a live report built from current system state.</div>
            )}
          </div>
        </Panel>
      </div>
    </div>
  );
}
